### ISSUE TITLE
Roots compatibility issues with PostCss and plugins?

### ISSUE THREAD

**Issue by musamanyama** [carrot/roots-www#37]
I just started on roots today and had a constant fear for a grid system package I'm using that shifted to postcss for good.

I'm using lost grid system and the official package on npm is somehow not compatible with roots (at least to my poor understanding maybe) . When I install lost and require it in app.coffee file then run roots watch

I faced my fears & got this error : 

```
compiling... [Error: TypeError: css.walkAtRules is not a function]

Potentially unhandled rejection [6] TypeError: css.walkAtRules is not a function
  at lostAtRule (/home/maotora/Projects/Sites/caramelbutterfly/node_modules/lost/lib/lost-at-rule.js:12:7)
  at /home/maotora/Projects/Sites/caramelbutterfly/node_modules/lost/lost.js:32:7
  at Array.forEach (native)
  at Renderer.<anonymous> (/home/maotora/Projects/Sites/caramelbutterfly/node_modules/lost/lost.js:31:10)
  at Renderer.use (/home/maotora/Projects/Sites/caramelbutterfly/node_modules/stylus/lib/renderer.js:203:6)
  at Stylus._render (/usr/lib/node_modules/roots/node_modules/accord/lib/adapters/stylus/0.x.js:103:14)
  at Stylus.Adapter.render (/usr/lib/node_modules/roots/node_modules/accord/lib/adapter_base.js:122:19)
  at CompilePass.compile_or_pass (/usr/lib/node_modules/roots/lib/compiler.js:522:27)
  at tryCatchReject (/usr/lib/node_modules/roots/node_modules/when/lib/makePromise.js:845:30)
  at runContinuation1 (/usr/lib/node_modules/roots/node_modules/when/lib/makePromise.js:804:4)
  at Fulfilled.when (/usr/lib/node_modules/roots/node_modules/when/lib/makePromise.js:592:4)
  at Pending.run (/usr/lib/node_modules/roots/node_modules/when/lib/makePromise.js:483:13)
  at Scheduler._drain (/usr/lib/node_modules/roots/node_modules/when/lib/Scheduler.js:62:19)
  at Scheduler.drain (/usr/lib/node_modules/roots/node_modules/when/lib/Scheduler.js:27:9)
  at _combinedTickCallback (node.js:370:9)
  at process._tickCallback (node.js:401:11)

^Cwatcher cancelled
```

Made a little follow up in the 
`/home/maotora/Projects/Sites/caramelbutterfly/node_modules/lost/lost.js:31:10` 
File and saw the dependency in Postcss which is calling the function which causes the whole break down.

I also tried using some more independent lost package from npm (lost-stylus), required it in the app.coffee then it too gives this rather disturbing error.
```
serv          pretty: true    jade:        sourcemap: true    'coffee-script':        sourcemap: true        use: [axis(), rupture(), autoprefixer(), lost()]    stylus:    ]        css_pipeline(files: 'assets/css/*.styl')        js_pipeline(files: 'assets/js/*.coffee'),    extensions: [    ignores: ['readme.md', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf']module.exports =css_pipeline = require 'css-pipeline'js_pipeline  = require 'js-pipeline'autoprefixer = require 'autoprefixer-stylus'rupture      = require 'rupture'axis         = require 'axis'lost         = require 'lost-stylus'
         ^]
^Cwatcher cancelled
```
Please help and if it's a Postcss compatibility issue, please support Postcss it will open a whole lot of doors for designers :)

**Comment by kylemac** [comment]
can you share your app.coffee? you'll need to add the postcss options in your app.coffee that includes the lost plugin. here's an example from another project: 

<img width="407" alt="screen shot 2016-03-05 at 5 22 30 pm" src="https://cloud.githubusercontent.com/assets/49507/13550932/0abb3444-e2f7-11e5-95e1-53837d3c7ba1.png">

**Comment by musamanyama** [comment]
Sure sure,
My app.coffee is at it's bare minimum with only lost added into it.

```
lost         = require 'lost'
axis         = require 'axis'
rupture      = require 'rupture'
autoprefixer = require 'autoprefixer-stylus'
js_pipeline  = require 'js-pipeline'
css_pipeline = require 'css-pipeline'

module.exports =
    ignores: ['readme.md', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf']

    extensions: [
        js_pipeline(files: 'assets/js/*.coffee'),
        css_pipeline(files: 'assets/css/*.styl')
    ]

    stylus:
        use: [axis(), rupture(), autoprefixer(), lost()]
        sourcemap: true

    'coffee-script':
        sourcemap: true

    jade:
        pretty: true
```

that was very fast indeed Thank you :)

**Comment by kylemac** [comment]
try this. ensure `postcss` and `lost` are in your package.json and installed

```coffee
lost         = require 'lost'
axis         = require 'axis'
rupture      = require 'rupture'
autoprefixer = require 'autoprefixer-stylus'
js_pipeline  = require 'js-pipeline'

module.exports =
    ignores: ['readme.md', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf']

    extensions: [js_pipeline(files: 'assets/js/*.coffee')]

    stylus:
        use: [axis(), rupture(), autoprefixer(), lost()]
        sourcemap: true
    
    postcss:
        use: [lost()]

    'coffee-script':
        sourcemap: true

    jade:
        pretty: true
```

**Comment by kylemac** [comment]
also, don't forget – you probably don't want to use the `stylus` along side the `postcss` plugins, because it'll likely confuse things. if you need to replace the functionality of autoprefixer, try https://github.com/simplaio/rucksack. axis + rupture don't have postcss ports yet

**Comment by musamanyama** [comment]
> you probably don't want to use the stylus along side the postcss plugins, because it'll likely confuse things

You meant like this ?

``` coffee
stylus:
        use: [axis(), rupture(), autoprefixer(), lost()]
        sourcemap: true

#And i should use this instead ?

stylus:
        use: [axis(), rupture(), autoprefixer()]
        sourcemap: true

```

I have done with and without the above code now and I get this error

```
3210#"! Utpd�x~maotora/Projects/Sites/caramelbutterfly/app.coffeeutf-8t
3210#"! Utpd�x~maotora/Projects/Sites/caramelbutterfly/app.coffeeutf-8
                       pretty: true    jade:        sourcemap: true    'coffee-script':        use: [lost()]    postCss:        sourcemap: true        use: [axis(), rupture(), autoprefixer()]    stylus:    ]        css_pipeline(files: 'assets/css/*.styl')        js_pipeline(files: 'assets/js/*.coffee'),    extensions: [    ignores: ['readme.md', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf']module.exports =css_pipeline = require 'css-pipeline'js_pipeline  = require 'js-pipeline'autoprefixer = require 'autoprefixer-stylus'rupture      = require 'rupture'axis         = require 'axis'lost         = require 'lost'
^Cwatcher cancelled
```

I have reinstalled lost and postcss with --save instead of the prior --save-dev.

Here is my package.json file.

``` json
{
  "name": "caramelbutterfly",
  "description": "A blog about everything you need to know from caramelbutterfly",
  "dependencies": {
    "autoprefixer-stylus": "0.8.x",
    "axis": "0.5.x",
    "coffee-script": "^1.0.0",
    "css-pipeline": "0.3.x",
    "jade": "^1.0.0",
    "js-pipeline": "0.2.x",
    "jstransformer-marked": "^1.0.0",
    "lost": "^6.7.2",
    "marked": "0.3.x",
    "postcss": "^5.0.19",
    "rupture": "0.6.x",
    "stylus": "0.52.x"
  }
}

```

**Comment by musamanyama** [comment]
Actually it didn't work :( 
The errors were removed from the console but it's not really working as I can see you removed `css_pipeline`
but when I do this I get errors from my layout.jade views file that css() is not a function.

So I didn't remove it, instead I removed the stylus configuration as from your explanations.

No errors, but nothing works from my postcss plugins.

#### Here is what I added in master.styl

``` stylus
@import '_settings'

normalize-css()
base()

body
  padding: 80px
  lost-utility: edit //Only added this line to bring me to edit mode..

```
***and***

#### Here is my app.coffee now ..
``` coffee
lost         = require 'lost'
oldie        = require 'oldie'
animation    = require 'postcss-animation'
fakeId       = require 'postcss-fakeid'
rucksack     = require 'rucksack-css'
keyframes    = require 'postcss-mq-keyframes'
axis         = require 'axis'
rupture      = require 'rupture'
autoprefixer = require 'autoprefixer-stylus'
js_pipeline  = require 'js-pipeline'
css_pipeline = require 'css-pipeline'

module.exports =
    ignores: ['readme.md', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf', '**/*.swp']

    extensions: [
        js_pipeline(files: 'assets/js/*.coffee')
        css_pipeline(files: 'assets/css/*.styl')
    ]

    postCss:
        use: [lost(), oldie(), keyframes(), animation(), rucksack(), fakeId()],
        options:
            from: './assets/css/master.styl',
            to: './public/css/master.css'

    'coffee-script':
        sourcemap: true

    jade:
        pretty: true

    server:
        clean_urls: true

    open_browser: false
```

Please share a full example file of your app.coffee which uses postcss, it will be really helpful to see how **ninjas** do it. ;)

**Comment by snowe2010** [comment]
thank you so much @maotora that edit with the poststylus plugin fixed my issue perfectly!
